### ISSUE TITLE
Add courtyards around 0.1" PTH header footprints

### ISSUE THREAD

**Issue by sfe-SparkFro** [sparkfun/SparkFun-KiCad-Libraries#110]
First off, all footprints should really have a courtyard to ensure DRC catches any accidentally overlapping parts.

Second, if a user wants to solder headers onto a board, there needs to be clearance for the headers, which are 0.1" wide. It's easy to forget this when designing a tight layout, such as the instance below (the outer 2x 0402 footprints would interfere with a header)

![image](https://github.com/user-attachments/assets/cebe2fe3-2e22-473c-b9a0-d1ae8ecfe7be)

Just need to add courtyard rectangles 0.1" wide like so:

![image](https://github.com/user-attachments/assets/57808717-a62d-4d57-b957-fc395a850b5c)

**Comment by nseidle** [comment]
How about a much closer courtyard that would avoid collision with the standoff but still prevent components?

![image](https://github.com/user-attachments/assets/38cde81f-1778-4bb6-96f0-a56c52c99392)

![image](https://github.com/user-attachments/assets/0d558167-99ed-4e65-b09b-5d1a54ffb9cd)

Also, I've added screws and nuts for 4-40 and M3.

![image](https://github.com/user-attachments/assets/8d0d8fab-078f-40c9-8432-6a56dd3db1c5)

![image](https://github.com/user-attachments/assets/a3a171a9-509a-4f1e-8d63-45bd52c53495)
![image](https://github.com/user-attachments/assets/51f5ad8a-61d5-46df-b59f-1a313c67022d)

**Comment by SFE-Brudnerd** [comment]
My only argument against a tighter courtyard like what Nate suggests is if a user desires to populate with 0.1" headers then the black plastic could interfere.

**Comment by nseidle** [comment]
Good point. We could add the outline to layer User1:

![image](https://github.com/user-attachments/assets/39afbab2-3b2b-43ec-89df-4a39db9b1582)

It will pass collision errors but make the designer aware of the possible issue.

Good enough?

**Comment by SFE-Brudnerd** [comment]
WFM!

**Comment by PaulZC** [comment]
My vote would be F.Fab. I've been using User.1 for milling. I submitted a PR recently to move all User1 text to F.Fab. I'd prefer not to start using it again for things like this...

**Comment by PaulZC** [comment]
https://github.com/sparkfun/SparkFun-KiCad-Libraries/pull/106#issuecomment-2254102679

**Comment by nseidle** [comment]
Talking this over with @sfe-SparkFro, we elected to keep the rectangular courtyard so that it does throw an error, and then the designer can exclude the error if they're ok with the collision.

![image](https://github.com/user-attachments/assets/171569c7-374e-4713-a7f7-0aa489d14f9d)

Rectangular courtyards will land in a minute on main.
