### ISSUE TITLE
Change PTH pads to "F.Cu, B.Cu, and connected layers"

### ISSUE THREAD

**Issue by sfe-SparkFro** [sparkfun/SparkFun-KiCad-Libraries#113]
I believe all our footprints with PTH pads have the "Copper layers" setting set to "All copper layers" like so:

![image](https://github.com/user-attachments/assets/70f640f9-ed54-4544-8d1b-5cff7f881c33)

However I would like to suggest changing them all to "F.Cu, B.Cu, and connected layers"

![image](https://github.com/user-attachments/assets/245b1174-6491-49b3-9758-fdf6ced6e5fe)

This gives a lot more clearance between adjacent pads on inner layers, which is actually important for a board I'm working on with a lot of headers in the middle of the board. Below, the left pair of pads is set to "F.Cu, B.Cu, and connected layers" and the right pair are set to "All copper layers". With default track and DRC settings, I can route up to 3 tracks between the left pair, but only 1 track between the right pair:

![image](https://github.com/user-attachments/assets/80256745-227a-4aa6-a72c-d391a81ea5d7)

I think this change should be made to all PTH pads in our library. I don't see any downside to it other than taking time to update them all. But also open to discussion from others!

**Comment by nseidle** [comment]
WFM! Please make the changes.
