### ISSUE TITLE
Part request - PRT-13054

### ISSUE THREAD

**Issue by owlyowl** [sparkfun/SparkFun-KiCad-Libraries#117]
Hi I was wondering if it's possible to add this to the library please?

**Comment by nseidle** [comment]
Sure! Merged now. You can find it under SparkFun-Connectors/Raspberry_Pi* But please check my work. I haven't used this part in a design yet so let me know if you see any issues. It's largely just a combination of built-in KiCad parts.



![image](https://github.com/user-attachments/assets/facf8ecf-798c-4c28-ba19-7449cc91e59f)

![image](https://github.com/user-attachments/assets/ead031cd-3c88-4e02-876e-133118ca7478)

![image](https://github.com/user-attachments/assets/b5d65692-0c85-4341-b747-68b6e72dda4b)

**Comment by owlyowl** [comment]
Hi Nathan!
Thanks so much!!
