### ISSUE TITLE
Add voltage regulator parameters

### ISSUE THREAD

**Issue by sfe-SparkFro** [sparkfun/SparkFun-KiCad-Libraries#127]
We commonly add the voltage and current rating of regulators in schematics as external text like so:

![image](https://github.com/user-attachments/assets/f953944a-9914-409d-a03b-7791fcd99d5b)

I think it would make sense to add those ratings to the regulators themselves, similar to the capacitors in this screenshot.

**Comment by PaulZC** [comment]
It's a good suggestion... I included similar on the DC-DC converters:

![image](https://github.com/user-attachments/assets/fc41ab74-f473-40c1-b858-21a8d963ce2c)

![image](https://github.com/user-attachments/assets/9aab6b1d-3f08-4114-aea8-e346646a4f10)

![image](https://github.com/user-attachments/assets/fc96aa00-a2b8-4ac7-81fb-34b85c085126)

**Comment by nseidle** [comment]
I approve of all this. I haven't gotten a chance to get to it, so if you PR it, I'll make it so.
