### ISSUE TITLE
Soldermask expansion/margin overrides

### ISSUE THREAD

**Issue by sfe-SparkFro** [sparkfun/SparkFun-KiCad-Libraries#137]
A lot of footprints have a manual override for the soldermask. For example, most of our PTH pads have an expansion of 0.1016mm (0.004", which is uncomfortably close when I have a copper clearance of 0.005"):

![image](https://github.com/user-attachments/assets/faa4bf62-41bb-4a67-80e2-aead883624a6)

However other footprints have no override, such as our capacitors:

![image](https://github.com/user-attachments/assets/fe5545a1-4a2e-4dd3-a854-22e06e769bf6)

In general, what should the override be set to? And does it depend on the footprint?

Personally, I think all footprints should not override the soldermask expansion, it should instead be specified in the board setup like so:

![image](https://github.com/user-attachments/assets/c02ae343-0dc8-4d6a-a7fe-935913bfb780)

If that's what we decide, then we'll need to remove the override from all footprints.

**Comment by nseidle** [comment]
@edspark showed me the error in some of the FPC footprints (that have overrides but should not). 

IMO, FPs should *not* have overrides and we should rely on a global expansion if needed.

If you've got a recommended solution, I'm likely for it.
