### ISSUE TITLE
WDFN-8_6x5mm-SkinnyCenterPad solder mask on center pad does not respect mask expansion rule

### ISSUE THREAD

**Issue by sfe-SparkFro** [sparkfun/SparkFun-KiCad-Libraries#150]
I have a board with relatively tight settings:

* Solder mask expansion - 0.05mm (0.002in)
* Zone clearance - 0.127mm (0.005in)

The center pad and its solder mask are defined as polygons, which causes the mask to overlapping with the GND zone in the corners:

![image](https://github.com/user-attachments/assets/b07938eb-4c03-4808-8126-e68e58871357)

The center pad should defined as a pad, so the board's mask expansion rule is respected.

**Comment by nseidle** [comment]
Thanks for the fix!
