### ISSUE TITLE
KiCad 7.0 Error: Invalid zero-sized pad pinned to 1µm

### ISSUE THREAD

**Issue by Zumili** [sparkfun/SparkFun-KiCad-Libraries#30]
Hey guys, nice lib, but you still have some errors in 5 of your footprints. KiCad 7 does not like having a pad size of 0 (zero).
The second parameter of the ‘size’ attribute is 0 (such as ‘(size 1.8796 0)’), which must be a minimum of 1µm for KiCad 7.0+

The problematic footprints are:
1X01_OFFSET.kicad_mod
1X40_OFFSET.kicad_mod
2X3_OFFSET.kicad_mod
PSP_CONNECTOR.kicad_mod
STEREOJACK2.5MM_SPECIAL_POGOPINS.kicad_mod

I have attached an ugly, long error log for identifying the footprints with wrong sizes.
Should be a quick fix.

15:59:01: Invalid zero-sized pad pinned to 1µm in
file: SparkFun-KiCad-Libraries-master\Footprints\SparkFun-Connectors.pretty/1X01_OFFSET.kicad_mod
line: 20
offset: 113
15:59:01: Invalid zero-sized pad pinned to 1µm in
file: SparkFun-KiCad-Libraries-master\Footprints\SparkFun-Connectors.pretty/1X40_OFFSET.kicad_mod
line: 175
offset: 112
15:59:01: Invalid zero-sized pad pinned to 1µm in
file: SparkFun-KiCad-Libraries-master\Footprints\SparkFun-Connectors.pretty/1X40_OFFSET.kicad_mod
line: 176
offset: 115
15:59:01: Invalid zero-sized pad pinned to 1µm in
file: SparkFun-KiCad-Libraries-master\Footprints\SparkFun-Connectors.pretty/1X40_OFFSET.kicad_mod
line: 177
offset: 115
15:59:01: Invalid zero-sized pad pinned to 1µm in
file: SparkFun-KiCad-Libraries-master\Footprints\SparkFun-Connectors.pretty/1X40_OFFSET.kicad_mod
line: 178
offset: 115
15:59:01: Invalid zero-sized pad pinned to 1µm in
file: SparkFun-KiCad-Libraries-master\Footprints\SparkFun-Connectors.pretty/1X40_OFFSET.kicad_mod
line: 179
offset: 116
15:59:01: Invalid zero-sized pad pinned to 1µm in
file: SparkFun-KiCad-Libraries-master\Footprints\SparkFun-Connectors.pretty/1X40_OFFSET.kicad_mod
line: 180
offset: 115
15:59:01: Invalid zero-sized pad pinned to 1µm in
file: SparkFun-KiCad-Libraries-master\Footprints\SparkFun-Connectors.pretty/1X40_OFFSET.kicad_mod
line: 181
offset: 116
15:59:01: Invalid zero-sized pad pinned to 1µm in
file: SparkFun-KiCad-Libraries-master\Footprints\SparkFun-Connectors.pretty/1X40_OFFSET.kicad_mod
line: 182
offset: 116
15:59:01: Invalid zero-sized pad pinned to 1µm in
file: SparkFun-KiCad-Libraries-master\Footprints\SparkFun-Connectors.pretty/1X40_OFFSET.kicad_mod
line: 183
offset: 116
15:59:01: Invalid zero-sized pad pinned to 1µm in
file: SparkFun-KiCad-Libraries-master\Footprints\SparkFun-Connectors.pretty/1X40_OFFSET.kicad_mod
line: 184
offset: 117
15:59:01: Invalid zero-sized pad pinned to 1µm in
file: SparkFun-KiCad-Libraries-master\Footprints\SparkFun-Connectors.pretty/1X40_OFFSET.kicad_mod
line: 185
offset: 116
15:59:01: Invalid zero-sized pad pinned to 1µm in
file: SparkFun-KiCad-Libraries-master\Footprints\SparkFun-Connectors.pretty/1X40_OFFSET.kicad_mod
line: 186
offset: 117
15:59:01: Invalid zero-sized pad pinned to 1µm in
file: SparkFun-KiCad-Libraries-master\Footprints\SparkFun-Connectors.pretty/1X40_OFFSET.kicad_mod
line: 187
offset: 117
15:59:01: Invalid zero-sized pad pinned to 1µm in
file: SparkFun-KiCad-Libraries-master\Footprints\SparkFun-Connectors.pretty/1X40_OFFSET.kicad_mod
line: 188
offset: 117
15:59:01: Invalid zero-sized pad pinned to 1µm in
file: SparkFun-KiCad-Libraries-master\Footprints\SparkFun-Connectors.pretty/1X40_OFFSET.kicad_mod
line: 189
offset: 117
15:59:01: Invalid zero-sized pad pinned to 1µm in
file: SparkFun-KiCad-Libraries-master\Footprints\SparkFun-Connectors.pretty/1X40_OFFSET.kicad_mod
line: 190
offset: 116
15:59:01: Invalid zero-sized pad pinned to 1µm in
file: SparkFun-KiCad-Libraries-master\Footprints\SparkFun-Connectors.pretty/1X40_OFFSET.kicad_mod
line: 191
offset: 117
15:59:01: Invalid zero-sized pad pinned to 1µm in
file: SparkFun-KiCad-Libraries-master\Footprints\SparkFun-Connectors.pretty/1X40_OFFSET.kicad_mod
line: 192
offset: 117
15:59:01: Invalid zero-sized pad pinned to 1µm in
file: SparkFun-KiCad-Libraries-master\Footprints\SparkFun-Connectors.pretty/1X40_OFFSET.kicad_mod
line: 193
offset: 117
15:59:01: Invalid zero-sized pad pinned to 1µm in
file: SparkFun-KiCad-Libraries-master\Footprints\SparkFun-Connectors.pretty/1X40_OFFSET.kicad_mod
line: 194
offset: 117
15:59:01: Invalid zero-sized pad pinned to 1µm in
file: SparkFun-KiCad-Libraries-master\Footprints\SparkFun-Connectors.pretty/1X40_OFFSET.kicad_mod
line: 195
offset: 116
15:59:01: Invalid zero-sized pad pinned to 1µm in
file: SparkFun-KiCad-Libraries-master\Footprints\SparkFun-Connectors.pretty/1X40_OFFSET.kicad_mod
line: 196
offset: 117
15:59:01: Invalid zero-sized pad pinned to 1µm in
file: SparkFun-KiCad-Libraries-master\Footprints\SparkFun-Connectors.pretty/1X40_OFFSET.kicad_mod
line: 197
offset: 117
15:59:01: Invalid zero-sized pad pinned to 1µm in
file: SparkFun-KiCad-Libraries-master\Footprints\SparkFun-Connectors.pretty/1X40_OFFSET.kicad_mod
line: 198
offset: 117
15:59:01: Invalid zero-sized pad pinned to 1µm in
file: SparkFun-KiCad-Libraries-master\Footprints\SparkFun-Connectors.pretty/1X40_OFFSET.kicad_mod
line: 199
offset: 117
15:59:01: Invalid zero-sized pad pinned to 1µm in
file: SparkFun-KiCad-Libraries-master\Footprints\SparkFun-Connectors.pretty/1X40_OFFSET.kicad_mod
line: 200
offset: 116
15:59:01: Invalid zero-sized pad pinned to 1µm in
file: SparkFun-KiCad-Libraries-master\Footprints\SparkFun-Connectors.pretty/1X40_OFFSET.kicad_mod
line: 201
offset: 117
15:59:01: Invalid zero-sized pad pinned to 1µm in
file: SparkFun-KiCad-Libraries-master\Footprints\SparkFun-Connectors.pretty/1X40_OFFSET.kicad_mod
line: 202
offset: 117
15:59:01: Invalid zero-sized pad pinned to 1µm in
file: SparkFun-KiCad-Libraries-master\Footprints\SparkFun-Connectors.pretty/1X40_OFFSET.kicad_mod
line: 203
offset: 117
15:59:01: Invalid zero-sized pad pinned to 1µm in
file: SparkFun-KiCad-Libraries-master\Footprints\SparkFun-Connectors.pretty/1X40_OFFSET.kicad_mod
line: 204
offset: 117
15:59:01: Invalid zero-sized pad pinned to 1µm in
file: SparkFun-KiCad-Libraries-master\Footprints\SparkFun-Connectors.pretty/1X40_OFFSET.kicad_mod
line: 205
offset: 116
15:59:01: Invalid zero-sized pad pinned to 1µm in
file: SparkFun-KiCad-Libraries-master\Footprints\SparkFun-Connectors.pretty/1X40_OFFSET.kicad_mod
line: 206
offset: 117
15:59:01: Invalid zero-sized pad pinned to 1µm in
file: SparkFun-KiCad-Libraries-master\Footprints\SparkFun-Connectors.pretty/1X40_OFFSET.kicad_mod
line: 207
offset: 117
15:59:01: Invalid zero-sized pad pinned to 1µm in
file: SparkFun-KiCad-Libraries-master\Footprints\SparkFun-Connectors.pretty/1X40_OFFSET.kicad_mod
line: 208
offset: 117
15:59:01: Invalid zero-sized pad pinned to 1µm in
file: SparkFun-KiCad-Libraries-master\Footprints\SparkFun-Connectors.pretty/1X40_OFFSET.kicad_mod
line: 209
offset: 117
15:59:01: Invalid zero-sized pad pinned to 1µm in
file: SparkFun-KiCad-Libraries-master\Footprints\SparkFun-Connectors.pretty/1X40_OFFSET.kicad_mod
line: 210
offset: 116
15:59:01: Invalid zero-sized pad pinned to 1µm in
file: SparkFun-KiCad-Libraries-master\Footprints\SparkFun-Connectors.pretty/1X40_OFFSET.kicad_mod
line: 211
offset: 117
15:59:01: Invalid zero-sized pad pinned to 1µm in
file: SparkFun-KiCad-Libraries-master\Footprints\SparkFun-Connectors.pretty/1X40_OFFSET.kicad_mod
line: 212
offset: 117
15:59:01: Invalid zero-sized pad pinned to 1µm in
file: SparkFun-KiCad-Libraries-master\Footprints\SparkFun-Connectors.pretty/1X40_OFFSET.kicad_mod
line: 213
offset: 117
15:59:01: Invalid zero-sized pad pinned to 1µm in
file: SparkFun-KiCad-Libraries-master\Footprints\SparkFun-Connectors.pretty/1X40_OFFSET.kicad_mod
line: 214
offset: 117
15:59:01: Invalid zero-sized pad pinned to 1µm in
file: SparkFun-KiCad-Libraries-master\Footprints\SparkFun-Connectors.pretty/2X3_OFFSET.kicad_mod
line: 41
offset: 120
15:59:01: Invalid zero-sized pad pinned to 1µm in
file: SparkFun-KiCad-Libraries-master\Footprints\SparkFun-Connectors.pretty/2X3_OFFSET.kicad_mod
line: 42
offset: 121
15:59:01: Invalid zero-sized pad pinned to 1µm in
file: SparkFun-KiCad-Libraries-master\Footprints\SparkFun-Connectors.pretty/2X3_OFFSET.kicad_mod
line: 43
offset: 116
15:59:01: Invalid zero-sized pad pinned to 1µm in
file: SparkFun-KiCad-Libraries-master\Footprints\SparkFun-Connectors.pretty/2X3_OFFSET.kicad_mod
line: 44
offset: 117
15:59:01: Invalid zero-sized pad pinned to 1µm in
file: SparkFun-KiCad-Libraries-master\Footprints\SparkFun-Connectors.pretty/2X3_OFFSET.kicad_mod
line: 45
offset: 119
15:59:01: Invalid zero-sized pad pinned to 1µm in
file: SparkFun-KiCad-Libraries-master\Footprints\SparkFun-Connectors.pretty/2X3_OFFSET.kicad_mod
line: 46
offset: 120
15:59:01: Invalid zero-sized pad pinned to 1µm in
file: SparkFun-KiCad-Libraries-master\Footprints\SparkFun-Connectors.pretty/PSP_CONNECTOR.kicad_mod
line: 12
offset: 32
15:59:01: Invalid zero-sized pad pinned to 1µm in
file: SparkFun-KiCad-Libraries-master\Footprints\SparkFun-Connectors.pretty/STEREOJACK2.5MM_SPECIAL_POGOPINS.kicad_mod
line: 21
offset: 128
15:59:01: Invalid zero-sized pad pinned to 1µm in
file: SparkFun-KiCad-Libraries-master\Footprints\SparkFun-Connectors.pretty/STEREOJACK2.5MM_SPECIAL_POGOPINS.kicad_mod
line: 22
offset: 129
15:59:01: Invalid zero-sized pad pinned to 1µm in
file: SparkFun-KiCad-Libraries-master\Footprints\SparkFun-Connectors.pretty/STEREOJACK2.5MM_SPECIAL_POGOPINS.kicad_mod
line: 23
offset: 123
15:59:01: Invalid zero-sized pad pinned to 1µm in
file: SparkFun-KiCad-Libraries-master\Footprints\SparkFun-Connectors.pretty/STEREOJACK2.5MM_SPECIAL_POGOPINS.kicad_mod
line: 24
offset: 121

**Comment by nseidle** [comment]
You are using 'SparkFun-Connectors" which is no longer in the main branch (master doesn't exist any longer). We deprecated our old footprints a few months ago - please see the [readme](https://github.com/sparkfun/SparkFun-KiCad-Libraries/tree/main). The new one is [SparkFun-Connector.pretty](https://github.com/sparkfun/SparkFun-KiCad-Libraries/tree/main/Footprints/SparkFun-Connector.pretty) and is significantly smaller than the pre v7 version, but should be much more curated.
