### ISSUE TITLE
Top/bottom and left/right pads have same orientation

### ISSUE THREAD

**Issue by jey5nd6** [sparkfun/SparkFun-KiCad-Libraries#5]
The footprint TQFP32-08 (at least) has all its pads oriented at 0º, but with the top/bottom pads having their height and width swapped from the left/right pads.  This means when Kicad does a Push Pad Properties the "don't modify pads with different orientations" doesn't work.

The pads should have the same widths & heights, but one set should be rotated 90º from the other.

Ref: https://bugs.launchpad.net/kicad/+bug/1836137

**Comment by nseidle** [comment]
Sorry for the late reply! We've recently taken a new approach to this library. The TQFP footprint is not yet imported in the latest release. When we do add TQFP32 we'll be sure to base it on KiCad's FP and/or making sure we set the height/width correctly.
